# Generated by Django 2.2.16 on 2020-10-17 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_auto_20201017_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='gfdgfdgh',
        ),
        migrations.AddField(
            model_name='customtext',
            name='jhgjgjhgjhgjhgjhgjhgjhgjhgjhgjhgjhgjhgj',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customtext_jhgjgjhgjhgjhgjhgjhgjhgjhgjhgjhgjhgjhgj', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customtext',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
